version: '3'
services:
  beef:
    image: beef-xss
    build:
      context: .
      dockerfile: Dockerfile.beef
    ports:
      - 3000:3000
    env_file:
      ../ENVALL
    networks:
      - metasploit-framework_default
networks:
  metasploit-framework_default:
    external: true
