application_name: redteamz
namespaces:
- guise
- oompaloompas

endpoints:
  - type: pubportal
pubip: 45.56.104.173

environments:
- name: production
  status: 0
- name: canary
  status: 0
- name: staging
  status: 1
- name: development
  status: 1

vpn: 97.107.141.203
vpn_ips: 
- 97.107.141.203
- 192.168.219.0/24

loadbalancers:
- name: public
- name: private


# Payload Delivery & Static site Hosting
s3domains:
- bucket: bzrblog.s3-website-us-east-1.amazonaws.com
  certname: tls
  domains:
  - dragonfirestars.com 
  vpn: False


appdeploys:
- name: gophish
  #command:  ['python3', 'manage.py', 'runworker', 'channels']
  instancetype: c2c
  image:  us.gcr.io/redskysec/redteamz-beef

- name: beef
  #command:  ['python3', 'manage.py', 'runworker', 'channels']
  instancetype: c2c
  image:  us.gcr.io/redskysec/redteamz-gophish


databases:
  - name: postgres
    type: postgres
    version: latest
    image: postgres
    port: 5432
    volumes: 
      - name: db
        path: /var/lib/postgresql/data
    
  - name: redis
    type: redis
    image: redis:latest
    version: latest
    port: 6379
    volumes: []


cmvars:
      SERVERNAME: localhost

      #############################################
      # CRS Variables
      #############################################
      # Paranoia Level
      PARANOIA: 0
      # Inbound and Outbound Anomaly Score Threshold
      ANOMALYIN: 0
      ANOMALYOUT: 0
      PROXY: 0
      # Executing Paranoia Level
      # - EXECUTING_PARANOIA=2

      #######################################################
      # Reverse Proxy mode
      # (only available if SETPROXY was enabled during the
      # parent ModSecurity image)
      #######################################################
      # PROXYLOCATION: Application Backend of Reverse Proxy
      # - PROXYLOCATION=http://app:8000/
      #
      # If needed: add own httpd-proxy.conf (only available if SETPROXY
      # was enabled during build of parent ModSecurity image)
      #  - ./httpd-proxy.conf:/usr/local/apache2/conf/extra/httpd-proxy.conf

      #######################################################
      # Various CRS Variables with Default Values
      #######################################################
      #- ENFORCE_BODYPROC_URLENCODED=1
      #- ALLOWED_METHODS=GET HEAD POST OPTIONS
      #- ALLOWED_REQUEST_CONTENT_TYPE=application/x-www-form-urlencoded|multipart/form-data|text/xml|application/xml|application/soap+xml|application/x-amf|application/json|application/octet-stream|text/plain
      #- ALLOWED_REQUEST_CONTENT_TYPE_CHARSET=utf-8|iso-8859-1|iso-8859-15|windows-1252
      #- ALLOWED_HTTP_VERSIONS=HTTP/1.0 HTTP/1.1 HTTP/2 HTTP/2.0
      #- RESTRICTED_EXTENSIONS=.asa/ .asax/ .ascx/ .axd/ .backup/ .bak/ .bat/ .cdx/ .cer/ .cfg/ .cmd/ .com/ .config/ .conf/ .cs/ .csproj/ .csr/ .dat/ .db/ .dbf/ .dll/ .dos/ .htr/ .htw/ .ida/ .idc/ .idq/ .inc/ .ini/ .key/ .licx/ .lnk/ .log/ .mdb/ .old/ .pass/ .pdb/ .pol/ .printer/ .pwd/ .resources/ .resx/ .sql/ .sys/ .vb/ .vbs/ .vbproj/ .vsdisco/ .webinfo/ .xsd/ .xsx/
      #- RESTRICTED_HEADERS=/proxy/ /lock-token/ /content-range/ /if/
      #- STATIC_EXTENSIONS=/.jpg/ /.jpeg/ /.png/ /.gif/ /.js/ /.css/ /.ico/ /.svg/ /.webp/

      #######################################################
      # CRS Variables with Default Value unlimited
      #######################################################
      #- MAX_NUM_ARGS=255
      #- ARG_NAME_LENGTH=100
      #- ARG_LENGTH=400
      #- TOTAL_ARG_LENGTH=64000
      #- MAX_FILE_SIZE=1048576
      #- COMBINED_FILE_SIZES=1048576

    
